# Generated by Django 3.2.5 on 2021-10-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_auto_20210805_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetinfo',
            name='usdr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='one_time_pickup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suspend_end',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suspend_start',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='end_suspension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_suspension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_confirmed_pickup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='onetime_pickup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_suspension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.DeleteModel(
            name='BudgetInfo',
        ),
    ]
