# Generated by Django 3.2.5 on 2021-10-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20211004_1019'),
        ('employees', '0003_auto_20211005_1326'),
    ]

    operations = [
    ]
